---
title: "SP500"
author: "Matt Przybyla"
date: "7/29/2017"
output: html_document:
  keep_md: true
---

## Running tseries library after installing
```{r library}
library(tseries)
```

#1 Downloading the data
```{r get.hist.quote}
SNPdata <- get.hist.quote('^gspc',quote="Close")
```

#2 Calculate log returns
```{r log, sd, sqrt}
SNPret <- log(lag(SNPdata)) - log(SNPdata)
SNPvol <- sd(SNPret) * sqrt(250) * 100
```

#3 Calculate volatity measure 
```{r function}
get
Vol <- function(d, logrets)
{

	var = 0

	lam = 0

	varlist <- c()

	for (r in logrets) {

		lam = lam*(1 - 1/d) + 1
	
	var = (1 - 1/lam)*var + (1/lam)*r^2

		varlist <- c(varlist, var)

	}

	sqrt(varlist)
}
```

#4 Calculate volatility over different times using decay factors
```{r Vol}
volest <- Vol(10,SNPret)

volest2 <- Vol(30,SNPret)

volest3 <- Vol(100,SNPret)
```

#5 Plot results, overlaying volatility curves on the data

```{r plot, lines}
volestplot <- plot(volest,type="l")

lines(volest2,type="l",col="red")

lines(volest3, type = "l", col="blue")
```
